# Generated by Django 2.0.9 on 2018-12-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr_backup', '0003_dropbox_sync_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.EmailField(blank=True, default=None, help_text='The email address to send the backup to', max_length=255, null=True)),
                ('host', models.CharField(blank=True, default=None, help_text='The hostname of the server used to send emails with', max_length=255, null=True, verbose_name='Email server: Host')),
                ('port', models.IntegerField(blank=True, default=None, help_text='The port used by the email server to send mail', null=True, verbose_name='Email server: Port')),
                ('username', models.CharField(blank=True, default=None, help_text='Optional: The username required to authenticate on the email server', max_length=255, null=True, verbose_name='Email server: Username')),
                ('password', models.CharField(blank=True, default=None, help_text='Optional: The password required to authenticate on the email server', max_length=255, null=True, verbose_name='Email server: Password')),
                ('use_tls', models.BooleanField(default=False, help_text='Optional: Whether the email server uses TLS for encryption', verbose_name='Email server: Use TLS')),
                ('use_ssl', models.BooleanField(default=False, help_text='Optional: Whether the email server uses SSL for encryption', verbose_name='Email server: Use SSL')),
                ('latest_sync', models.DateTimeField(blank=True, default=None, help_text='Timestamp of latest email sent successfully. Automatically updated by application', null=True, verbose_name='Latest sync')),
                ('next_sync', models.DateTimeField(blank=True, default=None, help_text='Timestamp of next email sent. Automatically updated by application', null=True, verbose_name='Next sync')),
            ],
            options={
                'verbose_name': 'Email configuration',
                'default_permissions': (),
            },
        ),
    ]
